### ISSUE TITLE
Is the order of incoming messages important?

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/control-protocol#43]
https://github.com/knative-sandbox/control-protocol/blob/6e2383c7197da4070948cf98c1210734441f7fd4/pkg/service/service.go#L126

This goroutine makes it so there's no guarantee that the incoming messages are processed in order. Is that ok?

**Comment by slinkydeveloper** [comment]
I thought about that and I don't think message ordering is important, at least not in the use cases I have in mind (but this might change):

* When sending from controller to data plane, messages are sent sequentially -> controller sends a message, waits for the ack from the data plane, sends the next one, waits for the ack, etc... If the first ack is not received, the controller won't continue sending messages.
* When sending from the data plane to the controller -> Order is not important, because the controller receives messages from all its "controlled components".

But, I might be wrong here, so I prefer to keep this issue open in case new evidence come up of requiring to have strict ordering guarantee.
